### ISSUE TITLE
commit results?

### ISSUE THREAD

**Issue by r-lyeh** [miloyip/nativejson-benchmark#11]
hello milo,

could you commit and/or upload the results somewhere, so we can take a quick look before installing mingw/binutils/etc on windows platforms? : )

thanks in advance

**Comment by miloyip** [comment]
Yes. I am working on that.

But actually you can build it by VS2013 on Windows as  well.

**Comment by r-lyeh** [comment]
ah right. i saw the makefile but missed the premake script :) anyways it would be great to have the results in the landing page. keep up the good work :D
