### ISSUE TITLE
Please consider submitting this to the Boost Library Incubator

### ISSUE THREAD

**Issue by robertramey** [miloyip/nativejson-benchmark#12]
I've taken a cursory look at your package and it seems to me it might well be an interesting candidate for the Boost Library Incubator -   www.blincubator.com

It seems to fulfill the minimum requirements - tests and documentation and code.  The directory structure would need to be slightly changed to fit into the boost customs - but this is not a big deal - it's already very close.

The submission process itself is very simple and would give your library the visibility it deserves.

Robert Ramey

**Comment by miloyip** [comment]
This is not a library...

**Comment by mloskot** [comment]
I may be wrong, but my understanding was that @robertramey is suggesting to submit [rapidjson](https://github.com/miloyip/rapidjson) to BLI.

**Comment by robertramey** [comment]
Actually I think i got mixed up.

I’ve wanted someone to make json, yaml and other libraries for Boost.  A post on the mailing list led me to do a search for any existing libraries and suggest that the authors consider submitting to the boost incubator.  I had a few of these going and wasn’t careful enough to see that this library wasn’t what I was looking for so the suggestion wasn’t appropriate.  Sorry about that.

Of topic, I am impressed with performance results for rapidjson.  I don’t know whether or not it fits in the boost library “framework”.  It’s apparently very successful and does’nt need to be a boost library to get the attention it deserves so I wouldn’t bug the author about this.  of course if he wanted to try to get it into boost, I wouldn’t have any objection either.

personally I’m a great fan of boost::spirit for making parsers.  I like the concept and explicit decoupling of the grammar from the code.  So the benchmark results are discouraging to me.  So this little diversion into this project wasn’t what I was looking for, I found it quite useful and illuminating - thanks alot.


Robert Ramey
Robert Ramey Software Development
(805)569-3793
ramey@rrsd.com
www.rrsd.com

**Comment by miloyip** [comment]
I think the JSON spirit team may make use of the benchmark and optimize it (and/or spirit) in terms of performance and conformance. I hope this benchmark can help different libraries to improve. This benchmark itself may have its downside and should be improved as well. Looking forward to see feedback. Thanks.
