### ISSUE TITLE
ajson wanna try

### ISSUE THREAD

**Issue by lordoffox** [miloyip/nativejson-benchmark#47]
hi!
glad to see you.
interesting about https://github.com/lordoffox/ajson ?

**Comment by miloyip** [comment]
I seems that ajson cannot parse arbitrary JSON files, such as those in the benchmark suite. So I think it will be difficult to integrate it into this benchmark.

**Comment by lordoffox** [comment]
ajson design to parse json direct into C++ struct without dom.
Any way , Thanks for your listening.
