### ISSUE TITLE
Update JSON for Modern C++ to 2.0.9

### ISSUE THREAD

**Issue by nlohmann** [miloyip/nativejson-benchmark#76]
Can you please update JSON for Modern C++ to version 2.0.9, see https://github.com/nlohmann/json/releases/tag/v2.0.9 ?

**Comment by nlohmann** [comment]
Meanwhile, version 2.0.10 has been released, see https://github.com/nlohmann/json/releases/tag/v2.0.10.

**Comment by daoxunchen** [comment]
Why not create a pull request?

**Comment by nlohmann** [comment]
Good point - totally forgot about that... :-S
